import jsPDF from "jspdf";

type BriefData = {
  clientName: string;
  clientEmail?: string;
  projectName: string;
  projectType: string;
  goals: string;
  targetAudience?: string;
  timeline?: string;
  budget?: string;
  description?: string;
  moodboardUrls?: string[];
};

export function generatePDF(data: BriefData) {
  const doc = new jsPDF();
  let y = 20;

  // Header with purple accent
  doc.setFillColor(139, 92, 246); // #8B5CF6
  doc.rect(0, 0, 210, 15, "F");

  doc.setTextColor(255, 255, 255);
  doc.setFontSize(24);
  doc.setFont("helvetica", "bold");
  doc.text("Project Brief", 20, 10);

  y = 25;
  doc.setTextColor(0, 0, 0);

  // Client Info
  doc.setFontSize(16);
  doc.setFont("helvetica", "bold");
  doc.text("Client Information", 20, y);
  y += 8;

  doc.setFontSize(12);
  doc.setFont("helvetica", "normal");
  doc.text(`Client: ${data.clientName}`, 20, y);
  y += 6;
  if (data.clientEmail) {
    doc.text(`Email: ${data.clientEmail}`, 20, y);
    y += 6;
  }
  y += 4;

  // Project Info
  doc.setFontSize(16);
  doc.setFont("helvetica", "bold");
  doc.text("Project Details", 20, y);
  y += 8;

  doc.setFontSize(12);
  doc.setFont("helvetica", "normal");
  doc.text(`Project Name: ${data.projectName}`, 20, y);
  y += 6;
  doc.text(`Type: ${data.projectType}`, 20, y);
  y += 10;

  // Goals
  doc.setFontSize(16);
  doc.setFont("helvetica", "bold");
  doc.text("Project Goals", 20, y);
  y += 8;

  doc.setFontSize(12);
  doc.setFont("helvetica", "normal");
  const splitGoals = doc.splitTextToSize(data.goals, 170);
  doc.text(splitGoals, 20, y);
  y += splitGoals.length * 6 + 10;

  // Target Audience
  if (data.targetAudience) {
    doc.setFontSize(16);
    doc.setFont("helvetica", "bold");
    doc.text("Target Audience", 20, y);
    y += 8;

    doc.setFontSize(12);
    doc.setFont("helvetica", "normal");
    doc.text(data.targetAudience, 20, y);
    y += 10;
  }

  // Timeline & Budget
  if (data.timeline || data.budget) {
    doc.setFontSize(16);
    doc.setFont("helvetica", "bold");
    doc.text("Timeline & Budget", 20, y);
    y += 8;

    doc.setFontSize(12);
    doc.setFont("helvetica", "normal");
    if (data.timeline) {
      doc.text(`Timeline: ${data.timeline}`, 20, y);
      y += 6;
    }
    if (data.budget) {
      doc.text(`Budget: ${data.budget}`, 20, y);
      y += 10;
    }
  }

  // Additional Notes
  if (data.description) {
    if (y > 250) {
      doc.addPage();
      y = 20;
    }

    doc.setFontSize(16);
    doc.setFont("helvetica", "bold");
    doc.text("Additional Notes", 20, y);
    y += 8;

    doc.setFontSize(12);
    doc.setFont("helvetica", "normal");
    const splitDesc = doc.splitTextToSize(data.description, 170);
    doc.text(splitDesc, 20, y);
  }

  // Footer
  const pageCount = doc.internal.pages.length - 1;
  for (let i = 1; i <= pageCount; i++) {
    doc.setPage(i);
    doc.setFontSize(10);
    doc.setTextColor(150, 150, 150);
    doc.text(`Generated by Briefed • Page ${i} of ${pageCount}`, 20, 285);
  }

  // Save
  doc.save(`${data.projectName.replace(/\s+/g, "_")}_brief.pdf`);
}
